import "../globals.css";
import Menu from "../components/menu/menu";
import Header from "../components/header/header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="dark:bg-zinc-900">
        <div className="flex flex-col  gap-2 p-2 h-screen">
          <header className="dark:text-gray-400">
            <Header />
          </header>

          <div className="flex flex-1 gap-2">
            <aside className="max-w-40">
              <Menu />
            </aside>
            <main
              className="
              bg-slate-50
               flex-1
               dark:bg-gray-800
               dark:text-gray-400
               rounded-ss-xl
               px-4 
               py-2"
            >
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
